[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$MWZMqTVGCEGoVcpZCyHkvA$0RrjkbCn1ksryg/ncyDcjeiniFcbVV64wJ1GHL5gDjKO7bxDP.WfSgHu1Mc146TrR9VHYO5hPLWFjWZ0LYyP9A

